# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Voronoi_config = debug

else ifeq ($(config),release)
  Voronoi_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Voronoi

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

Voronoi:
ifneq (,$(Voronoi_config))
	@echo "==== Building Voronoi ($(Voronoi_config)) ===="
	@${MAKE} --no-print-directory -C . -f Voronoi.make config=$(Voronoi_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f Voronoi.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Voronoi"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"